kind: PersistentVolume
apiVersion: v1
metadata:
  name: elastic-pv-volume4
  labels:
    type: local
spec:
  storageClassName:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data4"
    type: DirectoryOrCreate
